name: Whitesource Unified Agent Scan - .NET (dotnet)

on: [push, pull_request, workflow_dispatch]

jobs:

  build:
     
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
      
    - name: WhiteSource Unified Agent Scan
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        WS_APIKEY: ${{secrets.APIKEY}}
        WS_USERKEY: ${{secrets.USERKEY}}
        WS_WSS_URL: https://saas.whitesourcesoftware.com/agent
        WS_PRODUCTNAME: GH_${{github.event.repository.name}}
        WS_PROJECTNAME: ${{github.ref}}_Prioritize
        WS_ENABLEIMPACTANALYSIS: true
        WS_RESOLVEALLDEPENDENCIES: false
        WS_NUGET_RESOLVEDEPENDENCIES: true
        WS_NUGET_RUNPRESTEP: true
        WS_FILESYSTEMSCAN: false
        WS_GENERATEPROJECTDETAILSJSON: true
        WS_EXCLUDES: '**/build/** **/tests/**'
      run: |
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        echo Unified Agent downloaded successfully
        CSPROJ=$(basename $(find ./src -type f -wholename "*.csproj") .csproj)
        DLL=$(find ./ -type f -wholename "*/bin/Release/*/$CSPROJ.dll")
        echo $DLL will be added to appPath
        java -jar wss-unified-agent.jar -appPath $DLL -d ./src